
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: queue-master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: queue-master
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka
        image: gcr.io/sample-customer-264515/queue-master:kafka-demo
        imagePullPolicy: IfNotPresent
        name: queue-master
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: queue-master
  name: queue-master
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: queue-master
  sessionAffinity: None
  type: ClusterIP